services:
  minflask:
    build: .
    image: minflask
    container_name: minflask
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minflask.rule=Host(`minflask.cx-tech.net`)"
      - "traefik.http.routers.minflask.entrypoints=websecure"
      - "traefik.http.routers.minflask.tls.certresolver=myresolver"
      - "traefik.http.services.minflask.loadbalancer.server.port=4999"
    networks:
      - traefik_proxy
    environment:
      - PORT=4999
    # ports não precisa
    ports:
      - "4999:4999"
networks:
  traefik_proxy:
    external: true
