services:
    minflask:
        build: .
        image: minflask
        container_name: minflask
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.minflask.rule=Host(`minflask.cx-tech.net`)"
            - "traefik.http.routers.minflask.entrypoints=websecure"
            - "traefik.http.routers.minflask.tls.certresolver=myresolver"
            - "traefik.http.services.minflask.loadbalancer.server.port=${PORT:-4999}"
        networks:
            - traefik_proxy
        
        environment:
            - PORT=${PORT:-4999}
        
        ports:
            - "${PORT:-4999}:${PORT:-4999}"
        
networks:
    traefik_proxy:
        external: true